// src/constants/errors.ts
// Machine-readable error codes — matches PRD Section 18

export const ErrorCode = {
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  CONFIRM_TEXT_MISMATCH: 'CONFIRM_TEXT_MISMATCH',

  // Authentication
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',

  // Authorization
  FORBIDDEN: 'FORBIDDEN',
  CANNOT_SELF_DEMOTE: 'CANNOT_SELF_DEMOTE',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',

  // Rate limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Domain-specific
  TABLE_SESSION_EXPIRED: 'TABLE_SESSION_EXPIRED',
  TABLE_ALREADY_ASSIGNED: 'TABLE_ALREADY_ASSIGNED',
  ORDER_NOT_MODIFIABLE: 'ORDER_NOT_MODIFIABLE',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];
